contact_email = "jackzhi4716@gmail.com"
language = "en_US"
time_zone = "UTC"
site_name = "jacktest"
site_url = "http://localhost:8081"
default_avatar = "gravatar"
gravatar_base_url = "https://www.gravatar.com/avatar/"
allow_email_registrations = true
allow_new_registrations = true
allow_password_login = true
login_required = false
theme = "default"
navbar_style = "colored"
primary_color = "#0033ff"

allow_update_avatar = true
allow_update_bio = true
allow_update_display_name = true
allow_update_location = true
allow_update_username = true
allow_update_website = true

level = 2
restrict_answer = true
# 这几个关注一下
permalink = 1    #3或者4时，question会加密成短id
robots = "User-agent= *"
Disallow = ["/*?code*", "/answer/api", "/admin", "/search", "/install", "/review", "/users/login", "/users/register", "/users/account-recovery", "/users/oauth/*", "/users/*/*"]
Sitemap = "http://localhost:8080/sitemap.xml"





